### ISSUE TITLE
DBM voice pack is missing.

### ISSUE THREAD

**Issue by strickland** [DeadlyBossMods/DBM-Voicepack-VEM#16]
**Describe the bug**

**Do you have an error log of what happened?**

**To Reproduce**

**Screenshots**

**Did you try having DeadlyBossMods as the only enabled addon and everything else (especially something like ElvUI) disabled?**

**Which version of DeadlyBossMods are you using?**

**Was it working in a previous version? If yes, which was the last good one?**

**Additional context**

I am getting this msg in chat everytime I login. Even though I have the latest version & also I made sure to re-download and re-install it from github to see if the problem still exists.

[02:36:53] <DBM> Your selected DBM voice pack is missing some sounds supported by DBM. Some warning sounds will still play default sounds. Please download a newer version of voice pack or contact pack author for an update that contains missing audio

**Comment by MysticalOS** [comment]
You're probably still running VEM stand alone that's no longer maintained. make sure it's removed and the VEM installed is one included with CORE download

**Comment by strickland** [comment]
Thanks for the swift & quick response. but how do I make sure of this? I use curse app to download VEM and I write in the search box "DBM VEM" is there another way thats better?

**Comment by MysticalOS** [comment]
Yes, do not use curseforge to look for VEM at all, uninstall stand alone version, delete folder from addons folder, then just reinstall DBM-Core and it has VEM BUILT IN

**Comment by strickland** [comment]
Ah you mean I shouldn't download any VEM addon by itself and without it I still will have VEM as a plugin included with the DBM CORE? I got you.

**Comment by strickland** [comment]
I also don't need to download all the other components such as 

DBM - Mists of Pandaria
DBM - Mage tower
DBM - PvP mods

Do I delete those also? are they included with the core as well? Just checking...

**Comment by MysticalOS** [comment]
Those are still needed if doing that stuff.

Core is current core stuff, and current raids. and VEM

extras are pvp, 5 man dungeons, challenges (mage tower etc), and old raids

**Comment by strickland** [comment]
Hey man sorry for bothering you but I have deleted the folder VEM already and re-installed DBM core again, but still not working and when I go to DBM core options this is what appears in my list or spoken alerts see SS.

https://i.imgur.com/KKmNjgP.png

**Comment by MysticalOS** [comment]
how are you reinstalling it? did you reinstall it AFTER deleting VEM folder manually?

**Comment by strickland** [comment]
My steps are as follows..

Opened wow folder & deleted DBM-VEM
Opened cursefrog app and went to - Deadly Boss Mod (DBM) - right click that and click Reinstall.

Thats it, those are my steps.

**Comment by MysticalOS** [comment]
that should have fixed it, restart game maybe? and make sure VEM folder is actually enabled.

**Comment by strickland** [comment]
I did restart the game, what do you mean make sure vem folder enabled, where do I enable that, is it ingame?

**Comment by MysticalOS** [comment]
In the addons list

**Comment by strickland** [comment]
Thank you! I did reinstall one more time and it worked...problem is solved <3

**Comment by MysticalOS** [comment]
👍

**Comment by strickland** [comment]
Hey man, I know this is closed as I said its solved which it is but I am just trying to make sure that its working...I already have Deadly boss mod (DBM) which is core and it includes the VEM and inside of options I got spoken alerts VEM female..I thought it suppose to work, I also have DBM (BS & Vanilla mods) - then I did a timewalking shattered hands which is a BC dungeon but there was no spoken alerts at all. Is this normal or do I have another bug that needs fixing?

**Comment by MysticalOS** [comment]
You missed post that 5 man dungeons was a separate mod above. installing tbc and vanilla mods only installed old raids. you need DBM-Dungeons

**Comment by strickland** [comment]
Oh yea I also have this > Deadly Boss Mods (DBM) - Dungeons (All Dungeon Mods)

Still no sounds in timewalking from dbm, the dbm itself works fine in chat by sending some messages like "fight started" or "fight ended" with the bars, but the vem sounds are not still not working for me in timewalking (Havent tested other stuff)

**Comment by MysticalOS** [comment]
I mean some bosses just have few/no alerts. and vem is really only for special alerts not just generic target alerts

**Comment by strickland** [comment]
Alright thanks.
